<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HouseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $houses = array(
            array("address"=>"Dalweg 2","postalcode"=>"6821 JP","city"=>"Arnhem"),
            array("address"=>"Dalweg 4","postalcode"=>"6821 JP", 'city' => "Arnhem"),
            array("address"=>"Dalweg 6","postalcode"=>"6821 JP", 'city' => "Arnhem"),
            array("address"=>"Dalweg 8","postalcode"=>"6821 JP", 'city' => "Arnhem"),
            array("address"=>"Dalweg 10","postalcode"=>"6821 JP", 'city' => "Arnhem"),
            array("address"=>"Dalweg 12","postalcode"=>"6821 JP", 'city' => "Arnhem"),
            array("address"=>"Dalweg 14","postalcode"=>"6821 JP","city"=>"Arnhem"),
            array("address"=>"Dalweg 16","postalcode"=>"6821 JP","city"=>"Arnhem"),
            array("address"=>"Dalweg 18","postalcode"=>"6821 JP","city"=>"Arnhem"),
            array("address"=>"Dalweg 20","postalcode"=>"6821 JP","city"=>"Arnhem"),
            array("address"=>"Dalweg 22","postalcode"=>"6821 JP","city"=>"Arnhem"),
            array("address"=>"Dalweg 24","postalcode"=>"6821 JP","city"=>"Arnhem"),
            array("address"=>"Dalweg 26","postalcode"=>"6821 JP","city"=>"Arnhem"),
            array("address"=>"Dalweg 28","postalcode"=>"6821 JP","city"=>"Arnhem"),
            array("address"=>"Dalweg 30","postalcode"=>"6821 JP","city"=>"Arnhem"),
            array("address"=>"Dalweg 32","postalcode"=>"6821 JP","city"=>"Arnhem"),
            array("address"=>"Dalweg 34","postalcode"=>"6821 JP","city"=>"Arnhem"),
            array("address"=>"Dalweg 36","postalcode"=>"6821 JP","city"=>"Arnhem"),
            array("address"=>"Dalweg 38","postalcode"=>"6821 JP","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 2","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 4","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 6","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 8","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 10","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 12","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 14","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 16","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 18","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 20","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 22","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 24","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 26","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 28","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 30","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 32","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 34","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 36","postalcode"=>"6821 JR","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 38","postalcode"=>"6821 JS","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 40","postalcode"=>"6821 JS","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 42","postalcode"=>"6821 JS","city"=>"Arnhem"),
            array("address"=>"Cattepoelseweg 1","postalcode"=>"6821 JV","city"=>"Arnhem"),
            array("address"=>"Cattepoelseweg 3","postalcode"=>"6821 JV","city"=>"Arnhem"),
            array("address"=>"Cattepoelseweg 5","postalcode"=>"6821 JV","city"=>"Arnhem"),
            array("address"=>"Cattepoelseweg 7","postalcode"=>"6821 JV","city"=>"Arnhem"),
            array("address"=>"Cattepoelseweg 9","postalcode"=>"6821 JV","city"=>"Arnhem"),
            array("address"=>"Cattepoelseweg 11","postalcode"=>"6821 JV","city"=>"Arnhem"),
            array("address"=>"Cattepoelseweg 13","postalcode"=>"6821 JV","city"=>"Arnhem"),
            array("address"=>"Cattepoelseweg 15","postalcode"=>"6821 JV","city"=>"Arnhem"),
            array("address"=>"Cattepoelseweg 17","postalcode"=>"6821 JV","city"=>"Arnhem"),
            array("address"=>"Cattepoelseweg 19","postalcode"=>"6821 JV","city"=>"Arnhem"),
            array("address"=>"Cattepoelseweg 21","postalcode"=>"6821 JV ","city"=>"Arnhem"),
            array("address"=>"Cattepoelseweg 23","postalcode"=>"6821 JV","city"=>"Arnhem"),
            array("address"=>"Cattepoelseweg 25","postalcode"=>"6821 JV","city"=>"Arnhem"),
            array("address"=>"Cattepoelseweg 27","postalcode"=>"6821 JV","city"=>"Arnhem"),
            array("address"=>"Cattepoelseweg 29","postalcode"=>"6821 JV","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 44","postalcode"=>"6821 JS","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 46","postalcode"=>"6821 JS","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 48","postalcode"=>"6821 JS","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 50","postalcode"=>"6821 JS","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 52","postalcode"=>"6821 JS","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 54","postalcode"=>"6821 JS","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 56","postalcode"=>"6821 JS","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 58","postalcode"=>"6821 JS","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 60","postalcode"=>"6821 JS","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 62","postalcode"=>"6821 JS","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 64","postalcode"=>"6821 JS","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 66","postalcode"=>"6821 JS","city"=>"Arnhem"),
            array("address"=>"Heselbergherweg 68","postalcode"=>"6821 JS","city"=>"Arnhem"),
            array("address"=>"Hommelseweg  405","postalcode"=>"6821 LK","city"=>"Arnhem"),
            array("address"=>"Hommelseweg  407","postalcode"=>"6821 LK","city"=>"Arnhem"),
            array("address"=>"Hommelseweg  409","postalcode"=>"6821 LK","city"=>"Arnhem"),
            array("address"=>"Hommelseweg  411","postalcode"=>"6821 LK","city"=>"Arnhem"),
            array("address"=>"Hommelseweg  413","postalcode"=>"6821 LK","city"=>"Arnhem"),
            array("address"=>"Hommelseweg  415","postalcode"=>"6821 LK","city"=>"Arnhem"),
            array("address"=>"Hommelseweg  417","postalcode"=>"6821 LK","city"=>"Arnhem"),
            array("address"=>"Hommelseweg 419","postalcode"=>"6821 LK","city"=>"Arnhem"),
            array("address"=>"Hommelseweg  421","postalcode"=>"6821 LK","city"=>"Arnhem"),
            array("address"=>"Hommelseweg  423","postalcode"=>"6821 LK","city"=>"Arnhem"),
            array("address"=>"Bachlaan 2","postalcode"=>"6815 DE","city"=>"Arnhem  "),
            array("address"=>"Bachlaan 4","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 6","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 8","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 10","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 12","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 14","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 16","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 18","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 20","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 22","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 24","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 26","postalcode"=>"6815 DE ","city"=>"Arnhem"),
            array("address"=>"Bachlaan 28","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 30","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 32","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 34","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 36","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 38","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 40","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 42","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 44","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Palestrinastraat 37","postalcode"=>"6815 DA","city"=>"Arnhem"),
            array("address"=>"Bachlaan 44","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 44","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 44","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 44","postalcode"=>"6815 DE","city"=>"Arnhem"),
            array("address"=>"Bachlaan 46","postalcode"=>"6815 DG","city"=>"Arnhem"),
            array("address"=>"Bachlaan 48","postalcode"=>"6815 DG","city"=>"Arnhem"),
            array("address"=>"Bachlaan 50","postalcode"=>"6815 DG","city"=>"Arnhem"),
            array("address"=>"Bachlaan 52","postalcode"=>"6815 DG","city"=>"Arnhem"),
            array("address"=>"Bachlaan 54","postalcode"=>"6815 DG","city"=>"Arnhem"),
            array("address"=>"Bachlaan 56","postalcode"=>"6815 DG","city"=>"Arnhem"),
            array("address"=>"Bachlaan 58","postalcode"=>"6815 DG","city"=>"Arnhem"),
            array("address"=>"Bachlaan 58","postalcode"=>"6815 DG","city"=>"Arnhem"),
            array("address"=>"Bachlaan 60","postalcode"=>"6815 DG","city"=>"Arnhem"),
            array("address"=>"Bachlaan 60","postalcode"=>"6815 DG","city"=>"Arnhem"),
            array("address"=>"Bachlaan 62","postalcode"=>"6815 DG","city"=>"Arnhem"),
            array("address"=>"Bachlaan 62","postalcode"=>"6815 DG","city"=>"Arnhem"),
            array("address"=>"Bachlaan 64","postalcode"=>"6815 DG","city"=>"Arnhem"),
            array("address"=>"Bachlaan 64","postalcode"=>"6815 DG","city"=>"Arnhem"),
            array("address"=>"Chopinstraat 5","postalcode"=>"6815 DC","city"=>"Arnhem"),
            array("address"=>"Chopinstraat 7","postalcode"=>"6815 DC","city"=>"Arnhem"),
            array("address"=>"Chopinstraat 9","postalcode"=>"6815 DC","city"=>"Arnhem"),
            array("address"=>"Chopinstraat 11","postalcode"=>"6815 DC","city"=>"Arnhem"),
            array("address"=>"Chopinstraat 13","postalcode"=>"6815 DC ","city"=>"Arnhem"),
            array("address"=>"Chopinstraat 15","postalcode"=>"6815 DC","city"=>"Arnhem"),
            array("address"=>"Chopinstraat 17","postalcode"=>"6815 DC","city"=>"Arnhem"),
            array("address"=>"Chopinstraat 19","postalcode"=>"6815 DC","city"=>"Arnhem"),
            array("address"=>"Chopinstraat 21","postalcode"=>"6815 DC","city"=>"Arnhem"),
            array("address"=>"Chopinstraat 23","postalcode"=>"6815 DC","city"=>"Arnhem"),
            array("address"=>"Händelstraat 34","postalcode"=>"6815 CZ","city"=>"Arnhem"),
            array("address"=>"Händelstraat 36","postalcode"=>"6815 CZ","city"=>"Arnhem"),
            array("address"=>"Händelstraat 38","postalcode"=>"6815 CZ","city"=>"Arnhem"),
            array("address"=>"Händelstraat 40","postalcode"=>"6815 CZ","city"=>"Arnhem"),
            array("address"=>"Händelstraat 42","postalcode"=>"6815 CZ","city"=>"Arnhem"),
            array("address"=>"Händelstraat 44","postalcode"=>"6815 CZ","city"=>"Arnhem"),
            array("address"=>"Händelstraat 46","postalcode"=>"6815 CZ","city"=>"Arnhem"),
            array("address"=>"Händelstraat 48","postalcode"=>"6815 CZ","city"=>"Arnhem"),
            array("address"=>"Händelstraat 50","postalcode"=>"6815 CZ","city"=>"Arnhem"),
            array("address"=>"Händelstraat 52","postalcode"=>"6815 CZ","city"=>"Arnhem"),
            array("address"=>"Händelstraat 54","postalcode"=>"6815 CZ","city"=>"Arnhem"),
            array("address"=>"Händelstraat 56","postalcode"=>"6815 CZ","city"=>"Arnhem"),
            array("address"=>"Händelstraat 58","postalcode"=>"6815 CZ","city"=>"Arnhem"),
            array("address"=>"Händelstraat 60","postalcode"=>"6815 CZ","city"=>"Arnhem"),
            array("address"=>"Naëll Tynnegieterstraat 30","postalcode"=>"6821 EX","city"=>"Arnhem"),
            array("address"=>"Naëll Tynnegieterstraat 30","postalcode"=>"6821 EX","city"=>"Arnhem"),
            array("address"=>"Naëll Tynnegieterstraat 30","postalcode"=>"6821 EX","city"=>"Arnhem"),
            array("address"=>"Naëll Tynnegieterstraat 32","postalcode"=>"6821 EX ","city"=>"Arnhem"),
            array("address"=>"Naëll Tynnegieterstraat 32","postalcode"=>"6821 EX","city"=>"Arnhem"),
            array("address"=>"Naëll Tynnegieterstraat 32","postalcode"=>"6821 EX","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 6","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 8","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 10","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 12","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 14","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 16","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 18","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 20","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 22","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 24","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 26","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 28","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 30","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 32","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 34","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 36","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 38","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 40","postalcode"=>"6825 AP","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 42","postalcode"=>"6825 AR","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 44","postalcode"=>"6825 AR","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 46","postalcode"=>"6825 AR","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 48","postalcode"=>"6825 AR","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 50","postalcode"=>"6825 AR","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 52","postalcode"=>"6825 AR","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 54","postalcode"=>"6825 AR","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 56","postalcode"=>"6825 AR","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 58","postalcode"=>"6825 AR","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 60","postalcode"=>"6826 AR","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 62","postalcode"=>"6825 AR","city"=>"Arnhem"),
            array("address"=>"Drakensteinlaan 64","postalcode"=>"6825 AR ","city"=>"Arnhem"),
            array("address"=>"Moersbergenlaan 9","postalcode"=>"6825 AM","city"=>"Arnhem"),
            array("address"=>"Moersbergenlaan 11","postalcode"=>"6825 AM","city"=>"Arnhem"),
            array("address"=>"Moersbergenlaan 13","postalcode"=>"6825 AM","city"=>"Arnhem"),
            array("address"=>"Moersbergenlaan 15","postalcode"=>"6825 AM","city"=>"Arnhem"),
            array("address"=>"Moersbergenlaan 17","postalcode"=>"6825 AM","city"=>"Arnhem"),
            array("address"=>"Moersbergenlaan 19","postalcode"=>"6825 AM","city"=>"Arnhem"),
            array("address"=>"Moersbergenlaan 21","postalcode"=>"6825 AM","city"=>"Arnhem"),
            array("address"=>"Moersbergenlaan 23","postalcode"=>"6825 AM","city"=>"Arnhem"),
            array("address"=>"Moersbergenlaan 25","postalcode"=>"6825 AM","city"=>"Arnhem"),
            array("address"=>"Moersbergenlaan 27","postalcode"=>"6825 AM","city"=>"Arnhem"),
            array("address"=>"Moersbergenlaan 29","postalcode"=>"6825 AM","city"=>"Arnhem"),
            array("address"=>"Moersbergenlaan 31","postalcode"=>"6825 AM","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 1","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 3","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 5","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 7","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 9","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 11","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 13","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 15","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 17","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 19","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 21","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 23","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 25","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 27","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 29","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 31","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 33","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Zorgvlietstraat 35","postalcode"=>"6825 AX","city"=>"Arnhem"),
            array("address"=>"Eduard van Beinumlaan 15","postalcode"=>"6815 GC","city"=>"Arnhem"),
            array("address"=>"Eduard van Beinumlaan 15","postalcode"=>"6815  GC","city"=>"Arnhem"),
            array("address"=>"Eduard van Beinumlaan 17","postalcode"=>"6815 GC","city"=>"Arnhem"),
            array("address"=>"Eduard van Beinumlaan 19","postalcode"=>"6815 GC","city"=>"Arnhem"),
            array("address"=>"Eduard van Beinumlaan 19","postalcode"=>"6815 GC","city"=>"Arnhem"),
            array("address"=>"Helena Coetsstraat 1","postalcode"=>"6815 GN","city"=>"Arnhem"),
            array("address"=>"Helena Coetsstraat 1","postalcode"=>"6815 GN","city"=>"Arnhem"),
            array("address"=>"Helena Coetsstraat 3","postalcode"=>"6815 GN","city"=>"Arnhem"),
            array("address"=>"Helena Coetsstraat 5","postalcode"=>"6815 GN","city"=>"Arnhem"),
            array("address"=>"Helena Coetsstraat 5","postalcode"=>"6815 GN","city"=>"Arnhem"),
            array("address"=>"Helena Coetsstraat 7","postalcode"=>"6815 GN","city"=>"Arnhem"),
            array("address"=>"Helena Coetsstraat 7","postalcode"=>"6815 GN","city"=>"Arnhem"),
            array("address"=>"Helena Coetsstraat 9","postalcode"=>"6815 GN","city"=>"Arnhem"),
            array("address"=>"Helena Coetsstraat 9","postalcode"=>"6815 GN","city"=>"Arnhem"),
            array("address"=>"Maria Hamstraat 1","postalcode"=>"6815 GP","city"=>"Arnhem"),
            array("address"=>"Maria Hamstraat 3","postalcode"=>"6815 GP","city"=>"Arnhem"),
            array("address"=>"Maria Hamstraat 5","postalcode"=>"6815 GP","city"=>"Arnhem"),
            array("address"=>"Slothouberstraat 1","postalcode"=>"6815 GS","city"=>"Arnhem"),
            array("address"=>"Slothouberstraat 3","postalcode"=>"6815 GS","city"=>"Arnhem"),
            array("address"=>"Slothouberstraat 5","postalcode"=>"6815 GS","city"=>"Arnhem"),
            array("address"=>"van Steenwijkstraat 1","postalcode"=>"6815 GR","city"=>"Arnhem"),
            array("address"=>"van Steenwijkstraat 3","postalcode"=>"6815 GR","city"=>"Arnhem"),
            array("address"=>"van Steenwijkstraat 5","postalcode"=>"6815 GR","city"=>"Arnhem"),

        );
        foreach($houses as $house) {
            DB::table('houses')->insert([
                'address' => $house['address'],
                'city' => $house['city'],
                'postalcode' => $house['postalcode'],
                'buildyear' => '2000',
                'surface' => '220',
                'accessible' => true,
                'condition_id' => '1',
                'created_at' => Carbon::now(),
            ]);
        }
    }
}
